name: 报告错误
description: 在使用 study_xxqg 的过程中遇到了错误
title: '[Bug]: '
labels: [ "bug?" ]

body:
  # User's README and agreement
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意填写错误回报！
        ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

        ### ❗ | 确定没有相同问题的ISSUE已被提出.
        ### 🌎| 请准确填写环境信息
        ### ❔ | 打开DEBUG模式复现，并提供出现问题前后至少 10 秒的完整日志内容。请自行删除日志内存在的个人信息及敏感内容。

        ## 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细项目文档!!!"
          required: true
        - label: "我已经在 [Issue Tracker](https://github.com/johlanse/study_xxqg/issues) 和文档中找过我要提出的问题，没有找到相同问题的ISSUE。"
          required: true
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
          required: true

  # User's data
  - type: markdown
    attributes:
      value: |
        ## 环境信息
        请根据实际使用环境修改以下信息。

  # Env | study_xxqg Version
  - type: input
    id: env-xxqg-ver
    attributes:
      label: studyXxqg 版本
    validations:
      required: true

  # Env | VM Version
  - type: dropdown
    id: env-vm-ver
    attributes:
      label: 运行环境
      description: 选择运行 study_xxqg 的系统版本
      options:
        - Windows (64)
        - Windows (32/x84)
        - MacOS
        - Linux
        - Ubuntu
        - CentOS
        - Debian
        - ArchLinux
        - 其它（请在下方说明）
    validations:
      required: true

  # Env | VM Arch
  - type: dropdown
    id: env-vm-arch
    attributes:
      label: 运行架构
      description: (可选) 选择运行 study_xxqg 的系统架构
      options:
        - AMD64
        - x86
        - ARM [32] (别名：AArch32 / ARMv7）
        - ARM [64] (别名：AArch64 / ARMv8）
        - 其它

  # Env | Use type
  - type: dropdown
    id: env-use-type
    attributes:
      label: 运行方式
      description: 选择程序的运行方式
      options:
        - Docker
        - Docker-Compose
        - 可执行文件（release的二进制）文件运行
        - 源码运行
    validations:
      required: true


  # Input | Reproduce
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
    validations:
      required: true

  # Input | Expected result
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  # Input | Actual result
  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true

  # Optional | CMD
  - type: textarea
    id: cmd
    attributes:
      label: docker运行命令或者docker-compose的内容
      render: golang

  # Optional | Logging
  - type: textarea
    id: logging
    attributes:
      label: 日志记录（可选）
      render: golang

  # Optional | Config
  - type: textarea
    id: config
    attributes:
      label: 配置信息（可选）
      render: yaml

  # Optional | Extra description
  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）